#!/bin/bash

WORK_PATH=$(cd `dirname $0`;pwd)
cd $WORK_PATH
mkdir httpd
cd httpd
yum groupinstall "Development tools" -y

yum install -y openssl-devel pcre-devel expat-devel wget



HTTPD_PREFIX=/opt/server/httpd

HTTPD_TAR_NAME=apr-1.7.0.tar.gz
HTTPD_TAR_UTIL_NAME=apr-util-1.6.1.tar.gz
HTTPD_TAR_HTTPD_NAME=httpd-2.4.39.tar.bz2
WITH_MPM=$1
HTTPD_USER=$2

groupadd $HTTPD_USER
useradd $HTTPD_USER -g $HTTPD_USER -M -s /sbin/nologin

wget -c http://apache.spinellicreations.com//apr/$HTTPD_TAR_NAME
wget -c http://apache.spinellicreations.com//apr/$HTTPD_TAR_UTIL_NAME
wget -c http://apache.mirrors.tds.net//httpd/$HTTPD_TAR_HTTPD_NAME

tar -xvf $HTTPD_TAR_NAME
tar -xvf $HTTPD_TAR_UTIL_NAME
tar -xvf $HTTPD_TAR_HTTPD_NAME

cp -a ${HTTPD_TAR_UTIL_NAME/.tar.gz} ./${HTTPD_TAR_HTTPD_NAME/.tar.bz2}/srclib/apr-util
cp -a ${HTTPD_TAR_NAME/.tar.gz} ./${HTTPD_TAR_HTTPD_NAME/.tar.bz2}/srclib/apr

cd ${HTTPD_TAR_HTTPD_NAME/.tar.bz2}

./configure --prefix=$HTTPD_PREFIX \
 --enable-so \
 --enable-ssl \
 --enable-cgi \
 --enable-rewrite \
 --with-zlib \
 --with-pcre \
 --with-included-apr \
 --enable-modules=most \
 --enable-mpms-shared=all \
 --with-mpm=$WITH_MPM

make && make install

sed -e "s/^User daemon/User ${HTTPD_USER}/g" -e "s/^Group daemon/Group ${HTTPD_USER}/g"

${HTTPD_PREFIX}/bin/apachectl start

find $HTTPD_PREFIX