#!/bin/bash

WORK_PATH=$(cd `dirname $0`;pwd)
cd $WORK_PATH

yum groupinstall "Development tools" -y
yum install -y wget

HTTPD_PREFIX=/opt/server/httpd

HTTPD_TAR_NAME=apr-1.7.0.tar.gz
HTTPD_TAR_UTIL_NAME=apr-util-1.6.1.tar.gz
HTTPD_TAR_HTTPD_NAME=httpd-2.4.39.tar.bz2
WITH_MPM=$1
wget -c http://apache.spinellicreations.com//apr/$HTTPD_TAR_NAME
wget -c http://apache.spinellicreations.com//apr/$HTTPD_TAR_UTIL_NAME
wget -c http://apache.mirrors.tds.net//httpd/$HTTPD_TAR_HTTPD_NAME

tar -xvf $HTTPD_TAR_NAME
tar -xvf $HTTPD_TAR_UTIL_NAM
tar -xvf $HTTPD_TAR_HTTPD_NAM

cp -a ${HTTPD_TAR_HTTPD_NAM/.tar.gz} ./${HTTPD_TAR_HTTPD_NAME/.tar.bz2}/srclib/apr
cp -a ${HTTPD_TAR_UTIL_NAME/.tar.gz} ./${HTTPD_TAR_HTTPD_NAME/.tar.bz2}/srclib/apr

cd ${HTTPD_TAR_HTTPD_NAME/.tar.bz2}


./configure --prefix=$HTTPD_PREFIX \
 --enable-so \
 --enable-ssl \
 --enable-cgi \
 --enable-rewrite \
 --with-zlib \
 --with-pcre \
 --with-included-apr \
 --enable-modules=most \
 --enable-mpms-shared=all \
 --with-mpm=$WITH_MPM
