#!/bin/bash

WORK_PATH=$(cd `dirname $0`;pwd)
cd $WORK_PATH

yum install gcc gcc-c++ autoconf automake zlib zlib-devel openssl openssl-devel -y

NG_USER=nginx
NG_GROUP=$NG_USER
NG_PREFIX=/opt/server/nginx

NG_TAR_NAME=nginx-1.16.1.tar.gz
wget http://nginx.org/download/$NG_TAR_NAME
tar xvf $NG_TAR_NAME
cd ${NG_TAR_NAME/.tar.gz}


groupadd $NG_GROUP
useradd $NG_USER -g $NG_USER -M -s /sbin/nologin


./configure \
--user=$NG_USER \
--group=$NG_GROUP \
--prefix=$NG_PREFIX \
--pid-path=$NG_PREFIX/run/nginx.pid \
--lock-path=$NG_PREFIX/lock/nginx.lock \
--with-http_ssl_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_gzip_static_module \
--with-http_stub_status_module

make

make install

$NG_PREFIX/sbin/nginx -t
$NG_PREFIX/sbin/nginx

find $NG_PREFIX